# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ENV['APIDOC_SECRET_KEY_BASE_' + ENV['APIDOC_MODE']]

test:
  secret_key_base: 4f965a922aa75b943773852b0b270abb7712142fffdaf744432c6c9cc408dd934ccad54a5e96a94e776cd814baecf81767efa58ec7df7a78cc724553ba3e4977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ENV['APIDOC_SECRET_KEY_BASE_' + ENV['APIDOC_MODE']]
